"use client";
import Link from "next/link";
import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { DAILY_ITEMS, DAILY_LEVELS_GENZAI, DAILY_LEVELS_NINTEI, WORK_REASONS_GENZAI, WORK_REASONS_NINTEI, emptyState, newWaku, type BackSide, type MoushitateshoState, type Waku } from "@/data/moushitatesho/types";
import { clearMoushitatesho, loadMoushitatesho, saveMoushitatesho } from "@/lib/moushitatesho-storage";

const steps = ["はじめに", "基本", "請求のかた", "期間", "裏面（認定日頃）", "裏面（現在）", "日常生活状況", "その他・手帳", "印刷"];
const month = (s:string) => s ? `${s.slice(0,4)}年${Number(s.slice(5))}月` : "";
const monthNumber = (s:string) => s ? Number(s.slice(0,4))*12+Number(s.slice(5)) : NaN;

export default function MoushitateshoTool() {
  const [state,setState]=useState<MoushitateshoState|null>(null), [step,setStep]=useState(0), [noSave,setNoSave]=useState(false), [saved,setSaved]=useState("この端末に自動保存します"), [confirmDelete,setConfirmDelete]=useState(false);
  useEffect(()=>{ setState(loadMoushitatesho() ?? emptyState()); },[]);
  useEffect(()=>{ if(!state||noSave)return; const timer=setTimeout(()=>{ const ok=saveMoushitatesho({...state,updatedAt:new Date().toISOString()}); setSaved(ok?"ここまでの内容は自動で保存されています":"保存できませんでした。書き出しをご利用ください"); },500); return()=>clearTimeout(timer); },[state,noSave]);
  if(!state) return <p>読み込んでいます…</p>;
  const patch=(p:Partial<MoushitateshoState>)=>setState({...state,...p});
  const setWaku=(id:string,p:Partial<Waku>)=>patch({waku:state.waku.map(w=>w.id===id?{...w,...p}:w)});
  const applicable=(s:number)=>!(s===4&&state.seikyuuType==="jigojuushou")&&!(s===5&&state.seikyuuType==="honrai");
  const move=(n:number)=>{ let x=Math.max(0,Math.min(8,n)); while(x>0&&x<8&&!applicable(x)) x += n>step?1:-1; setStep(x); window.scrollTo({top:0,behavior:"smooth"}); };
  const exportJson=()=>{ const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download="moushitatesho-data.json"; a.click(); URL.revokeObjectURL(a.href); };
  const importJson=(f:File)=>{ const r=new FileReader(); r.onload=()=>{ try{const v=JSON.parse(String(r.result)); if(v.version!==1)throw 0; setState(v);}catch{alert("このファイルは読み込めませんでした");}}; r.readAsText(f); };
  return <div className="mt-tool">
    <header className="mt-head"><p className="dougu-kicker">申立書をつくる</p><h1>{steps[step]}</h1><div className="mt-progress" role="progressbar" aria-valuemin={1} aria-valuemax={9} aria-valuenow={step+1}>{steps.map((x,i)=><button key={x} className={i===step?"current":""} onClick={()=>applicable(i)&&move(i)} aria-label={`${i+1}. ${x}`} disabled={!applicable(i)}>{i+1}</button>)}</div><p className="mt-saved" role="status">{noSave?"共有端末モード：この端末には保存しません":saved}</p></header>
    <section className="mt-panel">{step===0&&<Intro noSave={noSave} setNoSave={setNoSave} exportJson={exportJson} importJson={importJson} confirmDelete={confirmDelete} setConfirmDelete={setConfirmDelete} onDelete={()=>{clearMoushitatesho();setState(emptyState());setConfirmDelete(false)}}/>}{step===1&&<Basic state={state} patch={patch}/>} {step===2&&<Claim state={state} patch={patch}/>} {step===3&&<Periods state={state} setWaku={setWaku} patch={patch}/>} {step===4&&<Back title="障害認定日頃" value={state.back.nintei} onChange={v=>patch({back:{...state.back,nintei:v}})} current={false}/>} {step===5&&<Back title="現在" value={state.back.genzai} onChange={v=>patch({back:{...state.back,genzai:v}})} current/>} {step===6&&<Daily state={state} patch={patch}/>} {step===7&&<Other state={state} patch={patch}/>} {step===8&&<Finish state={state}/>}</section>
    <footer className="mt-actions"><Link href="/" className="mt-subtle">中断する</Link><div>{step>0&&<button onClick={()=>move(step-1)}>戻る</button>}{step<8&&<button key={step} autoFocus className="mt-primary" onClick={()=>move(step+1)}>次へ</button>}</div></footer>
  </div>;
}
function Intro(p:any){return <><p className="mt-lead">発病から現在までを期間に分けて、申立書の下書きをつくります。空欄のまま進み、あとで手書きすることもできます。</p><aside className="mt-privacy"><strong>入力内容は、このブラウザの中だけに保存されます。</strong><p>サーバーへの送信、アカウント登録、AIによる生成や判定はありません。</p></aside><label className="mt-check"><input type="checkbox" checked={p.noSave} onChange={e=>p.setNoSave(e.target.checked)}/>共有の端末なので、この端末には保存しない</label><div className="mt-data"><button onClick={p.exportJson}>データを書き出す</button><label className="mt-file">データを読み込む<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&p.importJson(e.target.files[0])}/></label>{!p.confirmDelete?<button onClick={()=>p.setConfirmDelete(true)}>保存内容を削除</button>:<span>本当に削除しますか？ <button onClick={p.onDelete}>削除する</button> <button onClick={()=>p.setConfirmDelete(false)}>やめる</button></span>}</div></>}
function Basic({state,patch}:any){return <div className="mt-fields"><Field label="傷病名"><input value={state.byoumei} onChange={e=>patch({byoumei:e.target.value})}/></Field><Field label="発病日"><input type="date" value={state.hatsubyou} onChange={e=>patch({hatsubyou:e.target.value})}/></Field><Field label="初診日"><input type="date" value={state.shoshin} onChange={e=>patch({shoshin:e.target.value})}/></Field><Field label="生年月日"><input type="date" value={state.seinengappi} onChange={e=>patch({seinengappi:e.target.value})}/></Field></div>}
function Claim({state,patch}:any){return <div className="mt-choices">{[["honrai","本来請求（認定日請求）","障害認定日頃の欄を書きます"],["jigojuushou","事後重症請求","現在の欄を書きます"],["sokyuu","遡及請求","障害認定日頃と現在の両方を書きます"]].map(x=><label key={x[0]}><input type="radio" name="claim" checked={state.seikyuuType===x[0]} onChange={()=>patch({seikyuuType:x[0]})}/><span><strong>{x[1]}</strong><small>{x[2]}</small></span></label>)}</div>}
function Periods({state,setWaku,patch}:any){ const notices=useMemo(()=>periodNotices(state),[state]); const sort=()=>patch({waku:[...state.waku].sort((a,b)=>a.from.localeCompare(b.from))}); return <div id="kikan"><p>発病から現在までを、受診の有無や生活の変化ごとに分けます。公式の案内は3〜5年が目安です。</p>{notices.map((n,i)=><p className="mt-notice" key={i}>{n}{n.includes("並べ替え")&&<button onClick={sort}>日付順に並べ替える</button>}</p>)}<div className="mt-wakus">{state.waku.map((w:any,i:number)=><article key={w.id}><h2>期間 {i+1}{i>=5&&<small>続紙 {Math.floor((i-5)/5)+1}枚目</small>}</h2><div className="mt-date-row"><Field label="開始"><input type="month" value={w.from} onChange={e=>setWaku(w.id,{from:e.target.value})}/></Field><Field label="終了"><input type="month" value={w.to} onChange={e=>setWaku(w.id,{to:e.target.value})}/></Field></div><label className="mt-check"><input type="checkbox" checked={w.jushin} onChange={e=>setWaku(w.id,{jushin:e.target.checked})}/>この期間に受診した</label>{w.jushin&&<Field label="医療機関名"><input value={w.kikan} onChange={e=>setWaku(w.id,{kikan:e.target.value})}/></Field>}<OverflowTextarea value={w.text} onChange={(text:string)=>setWaku(w.id,{text})}/><button onClick={()=>patch({waku:state.waku.filter((x:any)=>x.id!==w.id)})}>この期間を削除</button></article>)}</div><button className="mt-add" onClick={()=>patch({waku:[...state.waku,newWaku()]})}>期間を追加する</button></div>}
function periodNotices(s:MoushitateshoState){const n:string[]=[];const w=s.waku; for(let i=0;i<w.length;i++){const a=w[i],len=monthNumber(a.to)-monthNumber(a.from)+1;if(len>60)n.push(`期間 ${i+1} は${Math.floor(len/12)}年${len%12}か月あります。3〜5年で区切るのが公式の案内です`);if(a.jushin&&!a.kikan)n.push(`期間 ${i+1} は受診した期間なので、医療機関名の欄があります`);if(i&&w[i-1].to&&a.from){const gap=monthNumber(a.from)-monthNumber(w[i-1].to)-1;if(gap>0)n.push(`${month(nextMonth(w[i-1].to))}から${month(prevMonth(a.from))}までが、どの枠にも入っていません`)}}if(w.some((x,i)=>i&&x.from<w[i-1].from))n.push("日付順に並べ替えますか");if(s.hatsubyou&&w[0]?.from&&w[0].from>s.hatsubyou.slice(0,7))n.push(`発病（${month(s.hatsubyou.slice(0,7))}）から最初の枠までが空いています`);const last=w[w.length-1];if(last?.to&&monthNumber(last.to)<monthNumber(new Date().toISOString().slice(0,7)))n.push(`${month(nextMonth(last.to))}から今日までが、どの枠にも入っていません`);return n}
const shiftMonth=(s:string,d:number)=>{const [y,m]=s.split("-").map(Number);const x=new Date(y,m-1+d,1);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}`}; const nextMonth=(s:string)=>shiftMonth(s,1),prevMonth=(s:string)=>shiftMonth(s,-1);
function OverflowTextarea({value,onChange}:any){const ref=useRef<HTMLDivElement>(null);const [ratio,setRatio]=useState(0);useEffect(()=>{let live=true;(document.fonts?.ready??Promise.resolve()).then(()=>{if(live&&ref.current)setRatio(value?ref.current.scrollHeight/ref.current.clientHeight:0)});return()=>{live=false}},[value]);return <Field label="当時の様子"><textarea rows={8} value={value} onChange={e=>onChange(e.target.value)}/><div ref={ref} className="mt-measure">{value||" "}</div>{ratio>1?<p className="mt-overflow">この枠に収まりません。続紙へ送るか、期間を分けると収まります</p>:ratio>.85?<p className="mt-notice">この枠はあと2行ほどで埋まります</p>:null}</Field>}
function Back({title,value,onChange,current}: {title:string,value:BackSide,onChange:(v:BackSide)=>void,current:boolean}){const reasons=current?WORK_REASONS_GENZAI:WORK_REASONS_NINTEI;return <><p>{title}の就労状況を、様式の選択肢に沿って記入します。</p><div className="mt-choices"><label><input type="radio" checked={value.work===true} onChange={()=>onChange({...value,work:true})}/>働いていた／いる</label><label><input type="radio" checked={value.work===false} onChange={()=>onChange({...value,work:false})}/>働いていなかった／いない</label></div>{value.work===false&&<div className="mt-fields">{reasons.map((r,i)=><label className="mt-check" key={r}><input type="checkbox" checked={value.reasons.includes(i)} onChange={e=>onChange({...value,reasons:e.target.checked?[...value.reasons,i]:value.reasons.filter(x=>x!==i)})}/>{r}</label>)}</div>}<div className="mt-fields"><Field label="職種"><input value={value.job} onChange={e=>onChange({...value,job:e.target.value})}/></Field><Field label="通勤方法"><input value={value.commuteMethod} onChange={e=>onChange({...value,commuteMethod:e.target.value})}/></Field><Field label="仕事中・仕事が終わったときの身体の調子"><textarea value={value.cond} onChange={e=>onChange({...value,cond:e.target.value})}/></Field></div></>}
function Daily({state,patch}:any){return <div className="mt-daily">{["nintei","genzai"].map((key:any)=>{if(key==="nintei"&&state.seikyuuType==="jigojuushou"||key==="genzai"&&state.seikyuuType==="honrai")return null;const levels=key==="nintei"?DAILY_LEVELS_NINTEI:DAILY_LEVELS_GENZAI;return <section key={key}><h2>{key==="nintei"?"障害認定日頃":"現在"}</h2>{DAILY_ITEMS.map((item,i)=><fieldset key={item}><legend>{item}</legend>{levels.map((l,j)=><label key={l}><input type="radio" name={`${key}-${i}`} checked={state.back[key].daily[i]===j+1} onChange={()=>patch({back:{...state.back,[key]:{...state.back[key],daily:{...state.back[key].daily,[i]:j+1}}}})}/>{l}</label>)}</fieldset>)}</section>})}</div>}
function Other({state,patch}:any){return <div className="mt-fields"><Field label="その他、日常生活で不便に感じたこと"><textarea rows={8} value={state.sonota} onChange={e=>patch({sonota:e.target.value})}/></Field><fieldset><legend>障害者手帳</legend>{[["ari","あり"],["nashi","なし"],["shinsei","申請中"]].map(x=><label className="mt-check" key={x[0]}><input type="radio" checked={state.techou===x[0]} onChange={()=>patch({techou:x[0]})}/>{x[1]}</label>)}</fieldset>{state.techou==="ari"&&<><Field label="手帳の種類"><input value={state.techouInfo.shurui} onChange={e=>patch({techouInfo:{...state.techouInfo,shurui:e.target.value}})}/></Field><Field label="等級"><input value={state.techouInfo.tokyu} onChange={e=>patch({techouInfo:{...state.techouInfo,tokyu:e.target.value}})}/></Field><Field label="氏名"><input value={state.techouInfo.namae} onChange={e=>patch({techouInfo:{...state.techouInfo,namae:e.target.value}})}/></Field></>}</div>}
function Finish({state}:{state:MoushitateshoState}){const printRef=useRef<HTMLAnchorElement>(null);useLayoutEffect(()=>{printRef.current?.focus()},[]);return <><p className="mt-lead">入力した内容を、公式様式の位置に重ねて印刷します。空欄はそのまま手書きできます。</p><Link ref={printRef} className="mt-print-link" href="/dougu/moushitatesho/insatsu" onClick={()=>{try{window.name=`moushitatesho:${JSON.stringify(state)}`}catch{}}}>印刷プレビューを開く</Link>
  <section className="mt-cross" aria-labelledby="mt-next"><h2 id="mt-next">ここからできること</h2><div className="dougu-cross">
    <Link className="dougu-band-card" href="/dougu/madoguchi"><b>年金事務所を探す</b><span>出す前に行き先を確かめる。管轄の窓口と予約のしかたを出します</span></Link>
    <Link className="dougu-band-card" href="/dougu/shorui"><b>必要書類をしらべる</b><span>ほかにそろえる書類を、持ち物と一緒に1枚にします</span></Link>
  </div></section></>}
function Field({label,children}:any){return <label className="mt-field"><span>{label}</span>{children}</label>}
