import { chromium } from "playwright";
import { spawn,execFileSync } from "node:child_process";
import { existsSync,mkdirSync,writeFileSync,readFileSync } from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import { fixtures,state } from "./fixtures.mjs";

const root=process.cwd(), out=path.join(root,"docs/verification/dougu-moushitatesho-2026-09-03"), pdf=path.join(out,"pdf"), png=path.join(out,"png"), overlay=path.join(out,"overlay");
mkdirSync(pdf,{recursive:true});mkdirSync(png,{recursive:true});mkdirSync(overlay,{recursive:true});
const chrome=process.env.CHROME_PATH||"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const server=spawn("npm",["run","start","--","-p","3110"],{cwd:root,stdio:"ignore"});
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); let ready=false;for(let i=0;i<60;i++){try{if((await fetch("http://127.0.0.1:3110/dougu/moushitatesho")).ok){ready=true;break}}catch{}await sleep(1000)}if(!ready){server.kill("SIGTERM");throw new Error("verification server did not start")}
const browser=await chromium.launch({headless:true,executablePath:chrome,args:["--font-render-hinting=none"]});
const rows=[], overflows=[], roundtrips=[];
async function startAndReachFinish(page){
  if(!await page.getByRole("button",{name:"次へ"}).isVisible().catch(()=>false)){
    const entry=page.getByRole("button",{name:/^(はじめる|続きから)$/}).first();
    await entry.waitFor();
    await entry.click();
  }
  for(let i=0;i<30;i++){
    if(await page.getByRole("link",{name:"印刷プレビューを開く"}).isVisible().catch(()=>false))return;
    const next=page.getByRole("button",{name:"次へ"});
    if(!await next.isVisible().catch(()=>false))break;
    await next.click();
  }
  await page.getByRole("link",{name:"印刷プレビューを開く"}).waitFor();
}
async function printFixture(name,data,format){const context=await browser.newContext();const p=await context.newPage();await p.addInitScript(v=>{window.name=`moushitatesho:${JSON.stringify(v)}`},data);await p.goto("http://127.0.0.1:3110/dougu/moushitatesho/insatsu");await p.locator(".mt-preview-stage").waitFor({state:"attached"});if(format==="a3"){await p.getByLabel("A3原寸").check();await p.locator(".mt-format-a3").waitFor()}await p.emulateMedia({media:"print"});await p.evaluate(()=>document.fonts?.ready);await sleep(500);const boxes=await p.locator(".mt-paper-text").evaluateAll(es=>es.map(e=>({text:e.textContent,scrollHeight:e.scrollHeight,clientHeight:e.clientHeight,overflow:e.scrollHeight>e.clientHeight,autoFit:e.dataset.autoFit,marked:e.dataset.overflow==="true",pt:parseFloat(e.style.fontSize)||10})));const warning=await p.evaluate(()=>{const el=document.querySelector(".mt-print-overflow");if(!el)return null;const m=(el.textContent||"").match(/収まらない欄が\s*(\d+)\s*か所/);return m?Number(m[1]):-1});overflows.push({name,format,count:boxes.filter(x=>x.overflow).length,autoFit:boxes.filter(x=>x.autoFit).length,marked:boxes.filter(x=>x.marked).length,minPt:Math.min(10,...boxes.map(x=>x.pt)),warning,boxes:boxes.filter(x=>x.overflow)});const file=path.join(pdf,`${name}-${format}.pdf`);if(!process.env.REUSE_PDFS)await p.pdf({path:file,format:format==="a3"?"A3":"A4",printBackground:true,preferCSSPageSize:true,margin:{top:"0",right:"0",bottom:"0",left:"0"}});await context.close();return file}
for(const [name,data] of fixtures)for(const format of ["a4","a3"]){const f=await printFixture(name,data,format);if(!process.env.REUSE_PDFS)execFileSync("pdftoppm",["-png","-r","300",f,path.join(png,`${name}-${format}`)]);}
// #6: rendering contract, 5 on the main page, 5 per continuation page, stable order and page numbers.
for(let n=1;n<=12;n++){const data=state(n);const context=await browser.newContext();const p=await context.newPage();await p.addInitScript(v=>{window.name=`moushitatesho:${JSON.stringify(v)}`},data);await p.goto("http://127.0.0.1:3110/dougu/moushitatesho/insatsu");await p.locator(".mt-preview-stage").waitFor();if(n>5)await p.locator(".mt-a4-cont").first().waitFor();const got=await p.evaluate(()=>({continuations:[...document.querySelectorAll(".mt-a4-cont")].map(s=>({no:s.querySelector(".mt-paper-text")?.textContent,items:[...s.querySelectorAll(".mt-paper-meta")].map(x=>x.textContent)}))}));const expectedCont=Math.ceil(Math.max(0,n-5)/5);rows.push({periods:n,main:Math.min(n,5),continuationPages:got.continuations.length,expectedContinuationPages:expectedCont,distribution:[`main:${Math.min(n,5)}`,...got.continuations.map((x,i)=>`cont${i+1}:${x.items.length}`)],numbers:got.continuations.map(x=>x.no),pass:got.continuations.length===expectedCont&&got.continuations.every((x,i)=>x.no===String(i+1))});await context.close()}
// #10 storage disabled, input to preview must complete and show an explicit save failure.
const c10=await browser.newContext();const p10=await c10.newPage();await p10.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new Error("disabled")};Storage.prototype.setItem=()=>{throw new Error("disabled")}});await p10.goto("http://127.0.0.1:3110/dougu/moushitatesho");await p10.getByRole("button",{name:"はじめる"}).click();await p10.getByLabel("この病気や症状が始まったのは、いつ頃ですか").fill("2020-01");await sleep(650);const saveMessage=await p10.getByRole("status").innerText();await startAndReachFinish(p10);await p10.getByRole("link",{name:"印刷プレビューを開く"}).click();await p10.waitForURL("**/insatsu");const storagePass=/保存できません/.test(saveMessage)&&await p10.getByRole("heading",{name:"印刷プレビュー"}).isVisible();await c10.close();
// #11 use the exact JSON produced by the export button, then import it and compare persisted state.
for(const [name,data] of fixtures){const c=await browser.newContext({acceptDownloads:true});const p=await c.newPage();await p.goto("http://127.0.0.1:3110/dougu/moushitatesho");await p.evaluate(v=>localStorage.setItem("shougainenkin-note:moushitatesho:v1",JSON.stringify(v)),data);await p.reload();await startAndReachFinish(p);await p.getByText("保存について",{exact:true}).click();const d1=await Promise.all([p.waitForEvent("download"),p.getByRole("button",{name:"下書きをファイルに書き出す(別の端末に持っていく)"}).click()]);const file=await d1[0].path();const exported=JSON.parse(readFileSync(file,"utf8"));await p.getByLabel("ファイルから読み込む").setInputFiles(file);const d2=await Promise.all([p.waitForEvent("download"),p.getByRole("button",{name:"下書きをファイルに書き出す(別の端末に持っていく)"}).click()]);const restored=JSON.parse(readFileSync(await d2[0].path(),"utf8"));let pass=true;try{assert.deepEqual(exported,restored);assert.equal(restored.waku.length,data.waku.length);assert.equal(restored.hatsubyou,data.hatsubyou)}catch{pass=false}roundtrips.push({name,pass});await c.close()}
// #12 Tab-only traversal; Enter activates the final link. Count focus losses.
const c12=await browser.newContext({viewport:{width:375,height:812}});const p12=await c12.newPage();await p12.goto("http://127.0.0.1:3110/dougu/moushitatesho");await p12.getByRole("button",{name:"はじめる"}).focus();let losses=0,reached=false;const focusState=()=>p12.evaluate(()=>{const e=document.activeElement;return{tag:e?.tagName,hidden:!e||getComputedStyle(e).display==="none"||getComputedStyle(e).visibility==="hidden",text:e?.textContent?.trim()}});await p12.keyboard.press("Enter");for(let screen=0;screen<15;screen++){if(await p12.getByRole("link",{name:"印刷プレビューを開く"}).isVisible().catch(()=>false))break;await p12.getByRole("button",{name:"次へ"}).waitFor();await p12.waitForFunction(()=>document.activeElement?.textContent?.trim()==="次へ").catch(()=>{losses++});await p12.keyboard.press("Enter")}await p12.getByRole("link",{name:"印刷プレビューを開く"}).waitFor();await p12.waitForFunction(()=>document.activeElement?.textContent?.trim()==="印刷プレビューを開く");const finalFocus=await focusState();const mobile=await p12.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}));if(finalFocus.text==="印刷プレビューを開く"){reached=true;await Promise.all([p12.waitForURL(/\/insatsu$/),p12.keyboard.press("Enter")])}const keyboardPass=reached&&losses===0&&mobile.scrollWidth===mobile.clientWidth;await c12.close();
await browser.close();server.kill("SIGTERM");
const projection=[];const compare=(name,format,pageNo,ref,crop=null,overlayName=null)=>{const generated=path.join(png,`${name}-${format}-${pageNo}.png`);if(!existsSync(generated))return;const args=[path.join(root,"scripts/verify-moushitatesho/projection.py"),path.join(root,"public/forms/moushitatesho",ref),generated];if(crop)args.push(`--crop=${crop}`);if(overlayName)args.push(`--overlay=${path.join(overlay,overlayName)}`);const raw=execFileSync("python3",args,{encoding:"utf8"});projection.push({name,format,page:pageNo,...JSON.parse(raw)})};for(const [name,data] of fixtures){compare(name,"a3",1,"main-1.png",null,name==="empty"?"front.png":null);compare(name,"a3",2,"main-2.png",null,name==="empty"?"back.png":null);compare(name,"a4",1,"main-1.png","top");compare(name,"a4",2,"main-1.png","bottom");compare(name,"a4",3,"main-2.png","top");compare(name,"a4",4,"main-2.png","bottom");const continuationCount=Math.ceil(Math.max(0,data.waku.length-5)/5);for(let i=0;i<continuationCount;i++){compare(name,"a3",3+i,"continuation-1.png",null,name==="seven-periods"&&i===0?"continuation.png":null);compare(name,"a4",5+i,"continuation-1.png")}}
const result={generatedAt:new Date().toISOString(),projection,distribution:rows,overflow:overflows,storage:{message:saveMessage,pass:storagePass},roundtrip:roundtrips,keyboard:{pass:keyboardPass,focusLosses:losses,reachedPrint:reached,...mobile}};
writeFileSync(path.join(out,"results.json"),JSON.stringify(result,null,2));
// #8 はみ出し。旧条件は「最大入力でもはみ出し0」だったが、当時の実装が 0.5pt まで
// 自動縮小して見かけ上0にしていたため、判定として成立していなかった(2026-09-03に是正)。
// いまは (a) 現実的な入力で縮小も警告も出ない (b) 最大入力でははみ出しを検出して
// 赤枠と件数表示が一致する (c) どの欄も8pt未満にしない、の3つで見る。
const byFixture=n=>overflows.filter(x=>x.name===n);
const p8a=byFixture("three-periods").length>0&&byFixture("three-periods").every(x=>x.autoFit===0&&x.count===0&&x.warning===null);
const p8b=byFixture("maximal").length>0&&byFixture("maximal").every(x=>x.count>0&&x.marked===x.count&&x.warning===x.count);
const p8c=overflows.every(x=>x.minPt>=8);
const p4=projection.every(x=>x.pass),p6=rows.every(x=>x.pass),p8=p8a&&p8b&&p8c,p11=roundtrips.every(x=>x.pass);
const md=`# 申立書ツール §14 未完了6項目 検証結果\n\n実行日時: ${result.generatedAt}\n\n| 項目 | 判定 | 再現結果 |\n|---|---|---|\n| #4 1mm以内 | ${p4?"○":"×"} | 最大 ${Math.max(...projection.map(x=>x.maxDeltaMm)).toFixed(3)} mm |\n| #6 続紙 | ${p6?"○":"×"} | 期間1〜12: ${p6?"一致":"不一致あり"} |\n| #8 はみ出し(自動縮小に頼らない) | ${p8?"○":"×"} | 現実的3期間 ${p8a?"○":"×"}(縮小0・警告0) / 最大入力 ${p8b?"○":"×"}(検出・赤枠・件数一致) / 最小フォント ${Math.min(...overflows.map(x=>x.minPt))}pt ${p8c?"○":"×"} |\n| #10 localStorage無効 | ${storagePass?"○":"×"} | ${saveMessage} / 印刷画面到達 |\n| #11 JSON往復 | ${p11?"○":"×"} | ${roundtrips.filter(x=>x.pass).length}/5 deepEqual |\n| #12 キーボード完走 | ${keyboardPass?"○":"×"} | focus消失 ${losses}、375px ${mobile.scrollWidth}/${mobile.clientWidth} |\n\n## #4 射影計測\n\n|状態|形式|ページ|検出線|最大差(mm)|\n|---|---|---:|---:|---:|\n${projection.map(x=>`|${x.name}|${x.format}|${x.page}|${x.lineCount}|${x.maxDeltaMm}|`).join("\n")}\n\n## #6 期間振り分け\n\n|期間数|本体|続紙|配置|No|判定|\n|---:|---:|---:|---|---|---|\n${rows.map(x=>`|${x.periods}|${x.main}|${x.continuationPages}|${x.distribution.join(", ")}|${x.numbers.join(", ")}|${x.pass?"○":"×"}|`).join("\n")}\n\n## #8 はみ出し\n\n判定条件(2026-09-03に変更): (a) 3期間の現実的な入力で自動縮小0・警告0 / (b) 12期間の最大入力で8ptでも収まらない欄を検出し、赤枠の数と画面の件数表示が一致 / (c) どの欄も8pt未満にしない。\n\n旧条件は「最大入力でもはみ出し0」だったが、当時の実装が0.5ptまで縮めて0にしていたため、判定になっていなかった。\n\n${overflows.map(x=>`- ${x.name}/${x.format}: ${x.count}欄`).join("\n")}\n\n## #11 JSON往復\n\n${roundtrips.map(x=>`- ${x.name}: ${x.pass?"○":"×"}`).join("\n")}\n\n## 再現方法\n\n\`npm run build && node scripts/verify-moushitatesho/verify.mjs\`\n`;
const lineDetails=`\n\n### 全検出線の差\n\n|状態|形式|ページ|方向|基準(px)|出力(px)|差(mm)|\n|---|---|---:|---|---:|---:|---:|\n${projection.flatMap(x=>x.lines.map(line=>`|${x.name}|${x.format}|${x.page}|${line.axis}|${line.referencePx}|${line.outputPx}|${line.deltaMm}|`)).join("\n")}\n\n50%重ね合わせ画像: \`overlay/front.png\`、\`overlay/back.png\`、\`overlay/continuation.png\``;
let mdFinal=md.replace("\n\n## #6 期間振り分け",`${lineDetails}\n\n## #6 期間振り分け`);for(const x of overflows)mdFinal=mdFinal.replace(`- ${x.name}/${x.format}: ${x.count}欄`,`- ${x.name}/${x.format}: 8ptでも収まらない ${x.count}欄(赤枠 ${x.marked}、画面の件数表示 ${x.warning??"なし"})、縮小した欄 ${x.autoFit}、最小 ${x.minPt}pt`);
writeFileSync(path.join(out,"RESULT.md"),mdFinal);console.log(mdFinal);if(!(p4&&p6&&p8&&storagePass&&p11&&keyboardPass))process.exitCode=1;
